package com.example.multi_tanent.crm.enums;



public enum NotificationModule {
  LEADS, OPPORTUNITY, LEADS_TASK, DASHBOARD_TASK, EVENT, CALL_REMINDER,
  KPI, QUOTATION, SO, INVOICES, PO,
  CLIENT_WHATSAPP_COMMUNICATION, CLIENT_EMAIL_COMMUNICATION,
  META_RESPONSE
}

